name: fibonacci_iterator
version: 1.1.0
author: Paul Fryzel <paul.fryzel@gmail.com>
description: A Fibonacci number iterator.
homepage: https://github.com/paulfryzel/dart-fibonacci-iterator
dependencies:
  unittest: '>=0.10.0 <0.11.0'
